"""Runtime helpers for the Phase 5 scaffold."""

from __future__ import annotations

from .prompt_compiler import (
    CompiledPromptArtifact,
    FrozenPromptAsset,
    FrozenPromptBundle,
    compile_frozen_prompt,
    load_frozen_prompt_bundle,
    write_compiled_prompt_artifacts,
)
from .prompt_serialization import ConversationTurn, normalize_turns, render_history, render_turn, render_turn_stream, serialize_turn
from .token_budget import (
    DEFAULT_INPUT_TOKEN_LIMIT,
    DEFAULT_RESERVED_OUTPUT_TOKENS,
    DEFAULT_TOTAL_TOKEN_LIMIT,
    EXPECTED_TOKENIZER_IDENTITY,
    FROZEN_MODEL_SLOT,
    InfrastructureOversizeError,
    OverflowClassification,
    TextTokenCount,
    TokenBudgetDecision,
    TokenBudgetExceededError,
    TokenBudgetPolicy,
    TokenizerIdentityMismatchError,
    TokenizerLoadError,
    TurnTokenCount,
    budget_decision_for_turn,
    build_exact_tokenizer,
    classify_overflow,
    count_tokens,
    enforce_token_budget,
    load_frozen_tokenizer_identity,
    summarize_text_token_count,
    summarize_turn_token_counts,
)
from .mcp_server_launcher import (
    LaunchVerification,
    McpServerLauncher,
    build_fastmcp_tool_catalog,
    ResetDispatchProbe,
    build_validated_server,
    discover_tool_names,
    is_loopback_host,
    probe_reset_dispatch,
)
from .agent_loop import (
    AgentLoopExecutionRecord,
    FrozenStateMachineControls,
    ModelBackend,
    ResetExecutor,
    StateTransitionRecord,
    load_frozen_state_machine_controls,
    run_frozen_agent_loop,
)
from .parser_adapter import (
    ModelOutputFailure,
    ParsedModelOutput,
    ParsedToolCall,
    parse_model_output,
    serialize_parsed_output,
)
from .session import CampaignSession
from .model_backend_adapter import (
    FrozenModelBackendAdapter,
    FrozenModelBackendIdentity,
    build_frozen_model_backend_adapter,
    load_frozen_model_backend_identity,
)
from .reset_controller import ResetController, ResetOutcome, load_reset_failure_retry_limit
from .tool_dispatch import (
    ForbiddenToolCallError,
    MissingToolParameterError,
    ToolDispatchError,
    ToolDispatchPolicy,
    ToolDispatchRecord,
    ToolExecutionFailure,
    ToolSpecification,
    UnknownToolCallError,
    dispatch_tool_calls,
)
from .workspace_isolation import AttemptWorkspaceIsolation, build_attempt_workspace_isolation

__all__ = [
    "CompiledPromptArtifact",
    "CampaignSession",
    "AttemptWorkspaceIsolation",
    "AgentLoopExecutionRecord",
    "ConversationTurn",
    "DEFAULT_INPUT_TOKEN_LIMIT",
    "DEFAULT_RESERVED_OUTPUT_TOKENS",
    "DEFAULT_TOTAL_TOKEN_LIMIT",
    "EXPECTED_TOKENIZER_IDENTITY",
    "LaunchVerification",
    "FrozenPromptAsset",
    "FrozenPromptBundle",
    "FrozenStateMachineControls",
    "FROZEN_MODEL_SLOT",
    "McpServerLauncher",
    "FrozenModelBackendAdapter",
    "FrozenModelBackendIdentity",
    "ModelBackend",
    "ModelOutputFailure",
    "InfrastructureOversizeError",
    "OverflowClassification",
    "ParsedModelOutput",
    "ParsedToolCall",
    "ResetController",
    "ResetDispatchProbe",
    "ResetOutcome",
    "ResetExecutor",
    "TextTokenCount",
    "TokenBudgetDecision",
    "TokenBudgetExceededError",
    "TokenBudgetPolicy",
    "TokenizerIdentityMismatchError",
    "TokenizerLoadError",
    "TurnTokenCount",
    "budget_decision_for_turn",
    "build_exact_tokenizer",
    "build_validated_server",
    "build_fastmcp_tool_catalog",
    "build_attempt_workspace_isolation",
    "build_frozen_model_backend_adapter",
    "classify_overflow",
    "compile_frozen_prompt",
    "dispatch_tool_calls",
    "discover_tool_names",
    "count_tokens",
    "enforce_token_budget",
    "ForbiddenToolCallError",
    "is_loopback_host",
    "load_frozen_prompt_bundle",
    "load_frozen_model_backend_identity",
    "load_frozen_state_machine_controls",
    "load_frozen_tokenizer_identity",
    "load_reset_failure_retry_limit",
    "normalize_turns",
    "MissingToolParameterError",
    "parse_model_output",
    "probe_reset_dispatch",
    "run_frozen_agent_loop",
    "render_history",
    "render_turn",
    "render_turn_stream",
    "serialize_parsed_output",
    "serialize_turn",
    "StateTransitionRecord",
    "ToolDispatchError",
    "ToolDispatchPolicy",
    "ToolDispatchRecord",
    "ToolExecutionFailure",
    "ToolSpecification",
    "summarize_text_token_count",
    "summarize_turn_token_counts",
    "UnknownToolCallError",
    "write_compiled_prompt_artifacts",
]
