"""
Module: verify_phase4_freeze.py
Purpose: Audits all validation artifacts generated by Phase 4 and produces final freeze reports.
"""
import os
import argparse
import sys
import logging

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from utils.reporting import generate_report

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def check_dependencies() -> list:
    prerequisites = [
        "phase4/validation/phase3_artifact_ingestion_report.md",
        "phase4/configs/model_set_freeze.yaml",
        "phase4/frozen_bundle/cryptographic_lock_manifest.json",
        "phase4/validation/payload_reference_validation_report.md"
    ]
    missing = [p for p in prerequisites if not os.path.exists(p)]
    return missing

def main():
    parser = argparse.ArgumentParser(description="Verify Phase 4 Freeze Status")
    parser.add_argument("--freeze-report", default="phase4/reports/phase4_protocol_freeze_report.md", help="Output")
    parser.add_argument("--decision-report", default="phase4/reports/phase4_go_no_go_decision.md", help="Output")
    parser.add_argument("--self-audit-report", default="phase4/validation/single_researcher_self_audit.md", help="Output")
    parser.add_argument("--final-verification-report", default="phase4/validation/final_phase4_verification_report.md", help="Output")
    args = parser.parse_args()

    missing = check_dependencies()
    
    status = "FAIL" if missing else "PASS"
    summary = "Upstream dependencies missing, freeze cannot proceed." if missing else "All critical validations passed."
    
    # Write the reports using the standard utility
    for r in [args.freeze_report, args.decision_report, args.self_audit_report, args.final_verification_report]:
        name = os.path.basename(r).replace('.md', '').replace('_', ' ').title()
        generate_report(
            filepath=r,
            title=name,
            purpose=f"Document the final status of the Phase 4 {name}.",
            inputs=["Phase 4 outputs"],
            checks=["Dependency resolution"],
            failures=missing,
            warnings=[],
            recommendations=["Resolve missing files before proceeding to Phase 4.5"] if missing else ["Proceed to Phase 4.5 dry-run."],
            summary=f"Status: {status}\n\n{summary}",
            evidence={"missing_dependencies": missing, "ready_for_phase5": not missing}
        )

    if missing:
        logging.error(f"Phase 4 freeze verification failed. Missing: {missing}")
        sys.exit(1)
        
    logging.info("[+] Phase 4 freeze verification passed.")
    sys.exit(0)

if __name__ == '__main__':
    main()
