"""
Module: verify_phase4_freeze.py
Purpose: Audits all validation artifacts generated by Phase 4 and produces final freeze reports.

Determinism Rule: All scripts must derive outputs exclusively from committed upstream artifacts.
No script may fabricate placeholder values, silently substitute defaults, infer missing evidence,
or generate synthetic metadata. When required evidence is unavailable, the script must explicitly
report DEPENDENCY_MISSING or NOT_MEASURABLE with justification.
"""
import os
import argparse
import sys
import logging
import json
import yaml
from pathlib import Path

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from utils.reporting import generate_report

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def validate_schema(filepath: str, data: any) -> bool:
    """Explicitly validates the expected schema for critical artifacts."""
    if "phase5_execution_manifest.json" in filepath:
        if not isinstance(data, dict):
            return False
        if not all(k in data and isinstance(data[k], dict) for k in ["hashes", "metrics", "dependencies"]):
            return False
            
        required_hashes = ["phase1_ledger_hash", "phase3_freeze_hash", "phase4_manifest_hash", "trial_order_sha256"]
        if not all(k in data["hashes"] for k in required_hashes):
            return False
            
        required_metrics = ["expected_trial_count", "expected_models", "expected_payload_count", "expected_defense_count"]
        if not all(k in data["metrics"] for k in required_metrics):
            return False
            
        required_deps = ["model_freeze", "payload_map", "defense_freeze", "statistical_plan", "trial_order", "cryptographic_manifest"]
        if not all(k in data["dependencies"] for k in required_deps):
            return False
            
    elif "cryptographic_lock_manifest.json" in filepath:
        if not isinstance(data, dict):
            return False
        if "manifest_hash" not in data or not isinstance(data["manifest_hash"], str):
            return False
        if "files" not in data or not isinstance(data["files"], dict):
            return False
    elif "payload_reference_map.json" in filepath:
        if not isinstance(data, dict) or not data:
            return False
        if not all(isinstance(v, str) or v is None for v in data.values()):
            return False
    elif "model_set_freeze.yaml" in filepath:
        if not data or (not isinstance(data, dict) and not isinstance(data, list)):
            return False
    return True

def check_dependencies() -> list:
    prerequisites = [
        "phase4/configs/payload_reference_map.json",
        "phase4/frozen_bundle/trial_order_core.csv",
        "phase4/configs/model_set_freeze.yaml",
        "phase4/frozen_bundle/cryptographic_lock_manifest.json",
        "phase4/frozen_bundle/phase5_execution_manifest.json",
        "phase4/configs/statistical_plan.yaml",
        "phase4/validation/token_budget_reverification_report.md",
        "phase4/validation/phase3_artifact_ingestion_report.md"
    ]
    missing = []
    
    for p in prerequisites:
        norm_path = Path(p)
        if not norm_path.exists():
            missing.append(f"{p} (Missing)")
            continue
            
        if norm_path.stat().st_size == 0:
            missing.append(f"{p} (Empty)")
            continue
            
        try:
            with open(norm_path, "r", encoding="utf-8") as f:
                if p.endswith(".json"):
                    data = json.load(f)
                    if not validate_schema(p, data):
                        missing.append(f"{p} (Schema Validation Failed)")
                elif p.endswith(".yaml") or p.endswith(".yml"):
                    data = yaml.safe_load(f)
                    if not validate_schema(p, data):
                        missing.append(f"{p} (Schema Validation Failed)")
                else:
                    f.read()
        except Exception as e:
            missing.append(f"{p} (Unreadable or Invalid Schema: {e})")
            
    return missing

def main():
    parser = argparse.ArgumentParser(description="Verify Phase 4 Freeze Status")
    parser.add_argument("--freeze-report", default="phase4/reports/phase4_protocol_freeze_report.md", help="Output")
    parser.add_argument("--decision-report", default="phase4/reports/phase4_go_no_go_decision.md", help="Output")
    parser.add_argument("--self-audit-report", default="phase4/validation/single_researcher_self_audit.md", help="Output")
    parser.add_argument("--final-verification-report", default="phase4/validation/final_phase4_verification_report.md", help="Output")
    args = parser.parse_args()

    missing = check_dependencies()
    
    if missing:
        status = "FAIL" # The user said "If required schema elements are missing, report FAIL instead of PASS."
        summary = f"Status: {status}\n\nUpstream dependencies missing or invalid, freeze cannot proceed."
        log_msg = f"Phase 4 freeze verification failed. Missing or invalid dependencies: {missing}"
    else:
        status = "PASS"
        summary = f"Status: {status}\n\nAll critical validations passed successfully."
        log_msg = "[+] Phase 4 freeze verification passed."
    
    reports = [args.freeze_report, args.decision_report, args.self_audit_report, args.final_verification_report]
    for r in reports:
        os.makedirs(os.path.dirname(r), exist_ok=True)
        name = os.path.basename(r).replace('.md', '').replace('_', ' ').title()
        generate_report(
            filepath=r,
            title=name,
            purpose=f"Document the final status of the Phase 4 {name}.",
            inputs=["Phase 4 outputs"],
            checks=["Dependency resolution, size > 0, readable, valid top-level schema"],
            failures=missing,
            warnings=[],
            recommendations=["Resolve missing files before proceeding to Phase 4.5"] if missing else ["Proceed to Phase 4.5 dry-run."],
            summary=summary,
            evidence={"missing_dependencies": missing, "ready_for_phase5": not missing}
        )

    if missing:
        logging.error(log_msg)
        sys.exit(1)
        
    logging.info(log_msg)
    sys.exit(0)

if __name__ == '__main__':
    main()
