"""Typed internal primitives for Phase 5."""

from __future__ import annotations

from .config import ArtifactRegistry, RegistryEntry, load_upstream_artifact_registry
from .enums import (
    AttackFamily,
    DefenseCondition,
    Density,
    MetadataSurfaceCondition,
    ModelSlot,
    PayloadCondition,
    SessionState,
    TrialOutcome,
    TrialPhase,
)
from .errors import (
    EXIT_CODE_REGISTRY,
    ExitCode,
    FrozenArtifactHashError,
    IdentifierValidationError,
    MissingFrozenSettingError,
    NotImplementedCommandError,
    Phase5Error,
    ProhibitedAliasError,
    SchemaInvariantError,
    SessionTransitionError,
    SyncSafetyError,
    UnknownEnumValueError,
)
from .identifiers import ArtifactId, AttemptId, BatchId, DatasetVersion, EventId, FrozenRowId, RunId, TrialId
from .invariants import (
    AcceptedAttemptRecord,
    FROZEN_TRIAL_FIELDS,
    FROZEN_TRIAL_FIELD_SET,
    FrozenTrialRow,
    PROHIBITED_FIELD_ALIASES,
    TrialAssessment,
    validate_hash_immutability,
    validate_primary_outcome,
    validate_session_execution_allowed,
    validate_single_accepted_attempt,
    validate_trial_row,
)
from .session import Phase5Session

__all__ = [
    "AcceptedAttemptRecord",
    "ArtifactId",
    "ArtifactRegistry",
    "AttackFamily",
    "AttemptId",
    "BatchId",
    "DatasetVersion",
    "DefenseCondition",
    "Density",
    "EXIT_CODE_REGISTRY",
    "EventId",
    "ExitCode",
    "FrozenArtifactHashError",
    "FrozenRowId",
    "FrozenTrialRow",
    "IdentifierValidationError",
    "MetadataSurfaceCondition",
    "MissingFrozenSettingError",
    "ModelSlot",
    "NotImplementedCommandError",
    "PayloadCondition",
    "Phase5Error",
    "Phase5Session",
    "PROHIBITED_FIELD_ALIASES",
    "ProhibitedAliasError",
    "RegistryEntry",
    "RunId",
    "SchemaInvariantError",
    "SessionState",
    "SessionTransitionError",
    "SyncSafetyError",
    "TrialAssessment",
    "TrialId",
    "TrialOutcome",
    "TrialPhase",
    "UnknownEnumValueError",
    "FROZEN_TRIAL_FIELDS",
    "FROZEN_TRIAL_FIELD_SET",
    "load_upstream_artifact_registry",
    "validate_hash_immutability",
    "validate_primary_outcome",
    "validate_session_execution_allowed",
    "validate_single_accepted_attempt",
    "validate_trial_row",
]
